#define SCREEN_SIZE 600
#define SCREEN_PADDING 50
#define LINE_THICKNESS 20
#define CELL_PADDING LINE_THICKNESS
#define GRID_SIZE 3
#define LINE_COUNT (GRID_SIZE - 1)
#define CELL_SIZE ((SCREEN_SIZE - SCREEN_PADDING * 2 - LINE_THICKNESS * 2) / GRID_SIZE)